//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeModel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bannerlar> Bannerlar { get; set; }
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<SayfaKategorileri> SayfaKategorileri { get; set; }
        public DbSet<Sayfalar> Sayfalar { get; set; }
        public DbSet<Sepet> Sepet { get; set; }
        public DbSet<SepetDetay> SepetDetay { get; set; }
        public DbSet<Urunler> Urunler { get; set; }
        public DbSet<UrunNumaralari> UrunNumaralari { get; set; }
        public DbSet<UrunRenkleri> UrunRenkleri { get; set; }
        public DbSet<UrunResimleri> UrunResimleri { get; set; }
        public DbSet<Uyeler> Uyeler { get; set; }
    }
}
