//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public Sepet()
        {
            this.SepetDetay = new HashSet<SepetDetay>();
        }
    
        public int id { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public string SiparisNumarasi { get; set; }
        public Nullable<int> SiparisDurumu { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
        public virtual ICollection<SepetDetay> SepetDetay { get; set; }
    }
}
