//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public Urunler()
        {
            this.SepetDetay = new HashSet<SepetDetay>();
            this.UrunResimleri = new HashSet<UrunResimleri>();
        }
    
        public int id { get; set; }
        public string Adi { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<double> indirim { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> TedarikSureci { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string RenkBilgisi { get; set; }
        public string NumaraBilgisi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual ICollection<SepetDetay> SepetDetay { get; set; }
        public virtual ICollection<UrunResimleri> UrunResimleri { get; set; }
    }
}
